### ISSUE TITLE
Automate injection of  corresponding author in first page footnote

### ISSUE THREAD

**Issue by nicolas-roelandt** [nicolas-roelandt/isprspaged#5]
Expected:

![image](https://user-images.githubusercontent.com/86657953/176185518-8854d3ec-ec77-4e63-a31a-011270694dc3.png)

What have been tried:

```css
@page:first{
  footpage.area::after{
    content : "* Corresponding author";
  }
}
```
